---
- name: install software packages
  apt:
    update_cache: yes
    name:
      - etckeeper
      - certbot
      - pwgen
      - mariadb-server
      - postfix
      - postfix-mysql
      - swaks
      - dovecot-mysql
      - dovecot-pop3d
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-managesieved
      - nginx
      - php
      - rspamd
      - fail2ban
      - ca-certificates
      - mutt
      - redis
  notify: restart dovecot
  
